version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.2.4

jobs:
  job-nightly:
    docker:
      - image: alpine:3.14

    steps:
      - add_ssh_keys:
          fingerprints:
            - "26:7f:22:ed:07:09:d2:15:c9:fb:43:29:64:2f:bd:b2"
      - run:
          name: Install git and curl
          command: |
            apk add \
                --update-cache \
                --no-progress \
                openssh \
                git \
                bash \
                curl \
                coreutils \
      - checkout
#      - shellcheck/install
#      - shellcheck/check:
#          pattern: update-reproducibility-summary.sh
      - run:
          command: |
            ./update-reproducibility-summary.sh
      - run:
          name: Configure git
          command: |
            git config user.email "nightly@reproducible-build.ci"
            git config user.name "Nightly Build Bot"
      - run:
          name: Commit Changes to README.md
          command: |
            .circleci/commit-readme.sh
      - run:
          name: Push Changes to README.md
          command: |
            git push

workflows:
  build_nightly:
    triggers:
      - schedule:
          cron: "50 20 * * *"
          filters:
            branches:
              only: master
    jobs:
      - job-nightly

  build_manual_nigthly:
    jobs:
      - approve-manual-nightly:
          type: approval
          filters:
            branches:
              only: master
      - job-nightly:
          requires:
            - approve-manual-nightly

